module.exports =

  ADD_LOCATION: 'ADD_LOCATION'
  REMOVE_LOCATION: 'REMOVE_LOCATION'
  SET_ACTIVE_LOCATION: 'SET_ACTIVE_LOCATION'
  CLEAR_ACTIVE_LOCATION: 'CLEAR_ACTIVE_LOCATION'

  TOGGLE_UNITS: 'TOGGLE_UNITS'

  SET_LOADING: 'SET_LOADING'
