module.exports =

  ADD_LOCATION: 'ADD_LOCATION'
  REMOVE_LOCATION: 'REMOVE_LOCATION'
  SET_ACTIVE_LOCATION: 'SET_ACTIVE_LOCATION'
  CLEAR_ACTIVE_LOCATION: 'CLEAR_ACTIVE_LOCATION'

  TOGGLE_UNITS: 'TOGGLE_UNITS'

  TOGGLE_NAVIGATION: 'TOGGLE_NAVIGATION'
  CLOSE_NAVIGATION: 'CLOSE_NAVIGATION'

  SET_LOADING: 'SET_LOADING'

  SET_ERROR: 'SET_ERROR'
  CLEAR_ERROR: 'CLEAR_ERROR'
